#! python3

# To calculate the size of file in a folder


import os


totalSize=0

for fileName in os.listdir("/home/<user>/Downloads"):
    if os.path.isfile(os.path.join("/home/<user>/Downloads",fileName)):
                      totalSize=totalSize+os.path.getsize(os.path.join("/home/<user>/Downloads",fileName))

print(totalSize)
                                                          
                    
